version: '3'

#TODO: Rails adicionar bunble em volume
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid  && yarn install --check-files && bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: "desenvolvendome-web"
    volumes:
      - .:/app
    ports:
      - "80:3000"
    depends_on:
      - db
    networks:
      - app
  db:
    image: postgres
    container_name: "desenvolvendome-db"
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    networks:
      - app
  redis:
    image: redis
    container_name: "desenvolvendome-redis"
    networks:
      - app
  sidekiq:
    build: .
    container_name: "desenvolvendome-sidekiq"
    volumes:
      - .:/app
    links:
      - db
      - redis
    command: bash -c "yarn install --check-files && bundle && bundle exec sidekiq -q default"
    networks:
      - app
networks:
  app:
    driver: bridge