version: '3'

services:
  desenvolvendome-postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: "desenvolvendome-redis"
    ports:
      - "6379:6379"